---
- name: installing nginx
  hosts: all 
  become: true
  tasks:
    - name: installing nginx
      apt:
        name: nginx
        state: present
      notify:
        - start nginx
           
  handlers:
    - name: start nginx
      service:
        name: nginx
        state: enabled
        