---
- hosts: samplenode
  gather_facts: false
  become: true
  tasks:
    - name: Install apache2
      apt:
        name: apache2
        state: present
      notify:
        - start apache2     # handler name
  handlers:
    - name: start apache2    # "Start httpd" handler block
      service:
        name: apache2
        state: started
