---
- name: Example Ansible playbook for Handlers
  hosts: all
  become: yes
  remote_user: ubuntu
  roles:
    - handlers

  handlers:
    - name: start apache2    # "Start httpd" handler block
      service:
        name: apache2
        state: restarted
    


