---
    - name: Install apache2
      apt:
        name: apache2
        state: present

  
    - name: copying file to index.html
      template:
        src: index.html
        dest: /var/www/html/index.html
      notify:
        - start apache2     # handler name

